export enum Status {
	AWAITING_CUSTOMER = "AWAITING_CUSTOMER",
	PENDING = "PENDING",
	IN_PROGRESS = "IN_PROGRESS",
	COMPLETED = "COMPLETED",
	CANCELED = "CANCELED",
  }
  
  export enum Department {
	MECHANICAL_WORKSHOP = "MECHANICAL_WORKSHOP",
	BODY_WORKSHOP = "BODY_WORKSHOP",
	PAINT_SHOP = "PAINT_SHOP",
	ADMINISTRATION = "ADMINISTRATION",
  }
  
  export enum Role {
	CUSTOMER = "CUSTOMER",
	EMPLOYEE = "EMPLOYEE",
	ADMIN = "ADMIN",
  }
  
